#!/bin/sh

gplaycli                                                              \
          --folder $FDROID_DIR/repo                                   \
          --config $FDROID_DIR/gplaycli.conf                          \
          --verbose                                                   \
          --yes                                                       \
          --progress                                                  \
          --append-version                                            \
          --additional-files                                          \
          --download $1
